name: test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        compiler: [g++, clang++]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        env:
          CXX: ${{ matrix.compiler }}
        run: bash tests/run_tests.sh
